// <auto-generated />
using EimakShas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EimakShas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250929222445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EimakShas.Models.Daf", b =>
                {
                    b.Property<int>("DafId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DafId"));

                    b.Property<int>("DafNumber")
                        .HasColumnType("int");

                    b.Property<int>("MasechtaId")
                        .HasColumnType("int");

                    b.Property<string>("Umid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DafId");

                    b.HasIndex("MasechtaId");

                    b.ToTable("Daf");
                });

            modelBuilder.Entity("EimakShas.Models.Masechta", b =>
                {
                    b.Property<int>("MasechtaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasechtaId"));

                    b.Property<int>("MasechtaDafCount")
                        .HasColumnType("int");

                    b.Property<string>("MasechtaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasechtaOrder")
                        .HasColumnType("int");

                    b.Property<int>("ShasCycleId")
                        .HasColumnType("int");

                    b.HasKey("MasechtaId");

                    b.HasIndex("ShasCycleId");

                    b.ToTable("Masechta");
                });

            modelBuilder.Entity("EimakShas.Models.ShasCycle", b =>
                {
                    b.Property<int>("ShasCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShasCycleId"));

                    b.Property<string>("ShasCycleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShasCycleId");

                    b.ToTable("ShasCycle");
                });

            modelBuilder.Entity("EimakShas.Models.Daf", b =>
                {
                    b.HasOne("EimakShas.Models.Masechta", "Masechta")
                        .WithMany("Dafim")
                        .HasForeignKey("MasechtaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masechta");
                });

            modelBuilder.Entity("EimakShas.Models.Masechta", b =>
                {
                    b.HasOne("EimakShas.Models.ShasCycle", "ShasCycle")
                        .WithMany("Masechtas")
                        .HasForeignKey("ShasCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShasCycle");
                });

            modelBuilder.Entity("EimakShas.Models.Masechta", b =>
                {
                    b.Navigation("Dafim");
                });

            modelBuilder.Entity("EimakShas.Models.ShasCycle", b =>
                {
                    b.Navigation("Masechtas");
                });
#pragma warning restore 612, 618
        }
    }
}
