// <auto-generated />
using System;
using EimakShas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EimakShas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215201433_addYomHashas_YomHashasDaf_ChavrisaRow")]
    partial class addYomHashas_YomHashasDaf_ChavrisaRow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EimakShas.Models.Daf", b =>
                {
                    b.Property<int>("DafId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DafId"));

                    b.Property<string>("DafLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DafNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted_Daf")
                        .HasColumnType("bit");

                    b.Property<int>("MasechtaId")
                        .HasColumnType("int");

                    b.HasKey("DafId");

                    b.HasIndex("MasechtaId");

                    b.ToTable("Dafim");
                });

            modelBuilder.Entity("EimakShas.Models.Masechta", b =>
                {
                    b.Property<int>("MasechtaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasechtaId"));

                    b.Property<int>("DafimFinished")
                        .HasColumnType("int");

                    b.Property<bool>("LastUmidDoubleSided")
                        .HasColumnType("bit");

                    b.Property<int>("MasechtaDafCount")
                        .HasColumnType("int");

                    b.Property<string>("MasechtaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasechtaOrder")
                        .HasColumnType("int");

                    b.Property<int>("PercentageFinished")
                        .HasColumnType("int");

                    b.HasKey("MasechtaId");

                    b.ToTable("Masechtas");
                });

            modelBuilder.Entity("EimakShas.Models.ShasInfo", b =>
                {
                    b.Property<int>("ShasInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShasInfoId"));

                    b.Property<int>("DafimCount_Shas")
                        .HasColumnType("int");

                    b.Property<int>("ShasPercentage")
                        .HasColumnType("int");

                    b.HasKey("ShasInfoId");

                    b.ToTable("ShasInfo");
                });

            modelBuilder.Entity("EimakShas.Models.Umid", b =>
                {
                    b.Property<int>("UmidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UmidId"));

                    b.Property<int>("DafId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted_Umid")
                        .HasColumnType("bit");

                    b.Property<string>("UmidLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UmidId");

                    b.HasIndex("DafId");

                    b.ToTable("Umidim");
                });

            modelBuilder.Entity("EimakShas.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("ChavrisaId")
                        .HasColumnType("int");

                    b.Property<bool>("DafPerDay")
                        .HasColumnType("bit");

                    b.Property<int>("DafimAmount")
                        .HasColumnType("int");

                    b.Property<int>("DafimFinished")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasText")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PercentageFinished")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("ChavrisaId")
                        .IsUnique()
                        .HasFilter("[ChavrisaId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EimakShas.Models.UserUmid", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UmidId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted_UserUmid")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "UmidId");

                    b.HasIndex("UmidId");

                    b.ToTable("UserUmidim");
                });

            modelBuilder.Entity("EimakShas.Models.YomHashas", b =>
                {
                    b.Property<int>("YomHashasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YomHashasId"));

                    b.Property<int>("BonusGoal")
                        .HasColumnType("int");

                    b.Property<int>("DafimCompleted")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<int>("PercentCompleted")
                        .HasColumnType("int");

                    b.HasKey("YomHashasId");

                    b.ToTable("YomHashas");
                });

            modelBuilder.Entity("EimakShas.Models.YomHashas_Daf", b =>
                {
                    b.Property<int>("YomHashas_DafId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YomHashas_DafId"));

                    b.Property<int>("DafId")
                        .HasColumnType("int");

                    b.HasKey("YomHashas_DafId");

                    b.HasIndex("DafId")
                        .IsUnique();

                    b.ToTable("YomHashas_Dafim");
                });

            modelBuilder.Entity("UserYomHashas_Daf", b =>
                {
                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.Property<int>("yomHashas_DafimYomHashas_DafId")
                        .HasColumnType("int");

                    b.HasKey("UsersUserId", "yomHashas_DafimYomHashas_DafId");

                    b.HasIndex("yomHashas_DafimYomHashas_DafId");

                    b.ToTable("UserYomHashas_Daf");
                });

            modelBuilder.Entity("EimakShas.Models.Daf", b =>
                {
                    b.HasOne("EimakShas.Models.Masechta", "Masechta")
                        .WithMany("Dafim")
                        .HasForeignKey("MasechtaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masechta");
                });

            modelBuilder.Entity("EimakShas.Models.Umid", b =>
                {
                    b.HasOne("EimakShas.Models.Daf", "Daf")
                        .WithMany("Umidim")
                        .HasForeignKey("DafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Daf");
                });

            modelBuilder.Entity("EimakShas.Models.User", b =>
                {
                    b.HasOne("EimakShas.Models.User", "Chavrisa")
                        .WithOne("LinkedTo")
                        .HasForeignKey("EimakShas.Models.User", "ChavrisaId");

                    b.Navigation("Chavrisa");
                });

            modelBuilder.Entity("EimakShas.Models.UserUmid", b =>
                {
                    b.HasOne("EimakShas.Models.Umid", "Umid")
                        .WithMany("UserUmidim")
                        .HasForeignKey("UmidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EimakShas.Models.User", "User")
                        .WithMany("UserUmidim")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Umid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EimakShas.Models.YomHashas_Daf", b =>
                {
                    b.HasOne("EimakShas.Models.Daf", "Daf")
                        .WithOne("YomHashas_Daf")
                        .HasForeignKey("EimakShas.Models.YomHashas_Daf", "DafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Daf");
                });

            modelBuilder.Entity("UserYomHashas_Daf", b =>
                {
                    b.HasOne("EimakShas.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EimakShas.Models.YomHashas_Daf", null)
                        .WithMany()
                        .HasForeignKey("yomHashas_DafimYomHashas_DafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EimakShas.Models.Daf", b =>
                {
                    b.Navigation("Umidim");

                    b.Navigation("YomHashas_Daf")
                        .IsRequired();
                });

            modelBuilder.Entity("EimakShas.Models.Masechta", b =>
                {
                    b.Navigation("Dafim");
                });

            modelBuilder.Entity("EimakShas.Models.Umid", b =>
                {
                    b.Navigation("UserUmidim");
                });

            modelBuilder.Entity("EimakShas.Models.User", b =>
                {
                    b.Navigation("LinkedTo");

                    b.Navigation("UserUmidim");
                });
#pragma warning restore 612, 618
        }
    }
}
