// <auto-generated />
using EimakShas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EimakShas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250930210053_addLastUmidDoubleSided")]
    partial class addLastUmidDoubleSided
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EimakShas.Models.Daf", b =>
                {
                    b.Property<int>("DafId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DafId"));

                    b.Property<int>("DafLetter")
                        .HasColumnType("int");

                    b.Property<int>("MasechtaId")
                        .HasColumnType("int");

                    b.HasKey("DafId");

                    b.HasIndex("MasechtaId");

                    b.ToTable("Dafim");
                });

            modelBuilder.Entity("EimakShas.Models.Masechta", b =>
                {
                    b.Property<int>("MasechtaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasechtaId"));

                    b.Property<bool>("LastUmidDoubleSided")
                        .HasColumnType("bit");

                    b.Property<int>("MasechtaDafCount")
                        .HasColumnType("int");

                    b.Property<string>("MasechtaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasechtaOrder")
                        .HasColumnType("int");

                    b.Property<int>("ShasCycleId")
                        .HasColumnType("int");

                    b.HasKey("MasechtaId");

                    b.HasIndex("ShasCycleId");

                    b.ToTable("Masechtas");
                });

            modelBuilder.Entity("EimakShas.Models.ShasCycle", b =>
                {
                    b.Property<int>("ShasCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShasCycleId"));

                    b.Property<string>("ShasCycleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShasCycleId");

                    b.ToTable("ShasCycles");
                });

            modelBuilder.Entity("EimakShas.Models.Umid", b =>
                {
                    b.Property<int>("UmidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UmidId"));

                    b.Property<int>("DafId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("UmidLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UmidId");

                    b.HasIndex("DafId");

                    b.HasIndex("UserId");

                    b.ToTable("Umidim");
                });

            modelBuilder.Entity("EimakShas.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EimakShas.Models.Daf", b =>
                {
                    b.HasOne("EimakShas.Models.Masechta", "Masechta")
                        .WithMany("Dafim")
                        .HasForeignKey("MasechtaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masechta");
                });

            modelBuilder.Entity("EimakShas.Models.Masechta", b =>
                {
                    b.HasOne("EimakShas.Models.ShasCycle", "ShasCycle")
                        .WithMany("Masechtas")
                        .HasForeignKey("ShasCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShasCycle");
                });

            modelBuilder.Entity("EimakShas.Models.Umid", b =>
                {
                    b.HasOne("EimakShas.Models.Daf", "Daf")
                        .WithMany("Umidim")
                        .HasForeignKey("DafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EimakShas.Models.User", null)
                        .WithMany("Umidim")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Daf");
                });

            modelBuilder.Entity("EimakShas.Models.Daf", b =>
                {
                    b.Navigation("Umidim");
                });

            modelBuilder.Entity("EimakShas.Models.Masechta", b =>
                {
                    b.Navigation("Dafim");
                });

            modelBuilder.Entity("EimakShas.Models.ShasCycle", b =>
                {
                    b.Navigation("Masechtas");
                });

            modelBuilder.Entity("EimakShas.Models.User", b =>
                {
                    b.Navigation("Umidim");
                });
#pragma warning restore 612, 618
        }
    }
}
